#禁用缓存
spring:
  thymeleaf:
    cache: false
    #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wj-vue
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
    #jpa正向工程
  jpa:
    hibernate:
    #根据实体类新建和更新表结构
      ddl-auto: update
      #显示sql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#server:
#  port: 8088
  #控制台打印生效的自动配置类
debug: true   
logging:
  level:
    com:
      zun: debug
  path: spring/log
  

   

